spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/remote_classroom}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:$Hubh@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=ap-south-1
aws.bucketName=remote-classroom-videos-02
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
gemini.api.key=${GEMINI_API_KEY}
openai.api.key=${OPENAI_API_KEY}